SWE-KASCHE/README.md

Erstmal vielen Dank für die Mitschriften, ich tue mir bei Kasche immer etwas schwer dran zu bleiben 😅 
Ich würde verschlage, dass Ganze etwas zu kürzen. Jedoch nicht inhaltlich sondern aus Sicht der LOCs. Aufzählungen in zehn Zeilen finde ich persönlich nicht so ansprechend. Daher hier das Ganze etwas komprimiert. Die Nummerierung der Überschriften würde ich auch wie im letzten Semester weglassen.

Mitschriften System-Entwurf 25.03.2021 kürzen

---

ASM-GUENTHER/README.md

Ähm, joa, so viel ist nicht passiert, aber er hat einen Hint auf eine mögliche Prüfungsfrage gegeben

PRO hwnah/Günther vom 30.03.2021

---

SWE-KASCHE/README.md

ist mir eben aufgefallen - dieses Modul heißt nicht Systemanalyse, sondern -entwurf

Systementwurf fix Heading

---

README.md

Ich hab noch nicht genug PRs!!11!elf!1!

add WPM1 modules to index Readme

---

PRO-KASCHE/README.md

Ich war mir mit @ZeroPointMax einig, dass der Part zu Blockchain und Krypto etwas durcheinander war. Hab das Ganze daher etwas von ihm abweichend aufgeräumt.

PRO: Mitschriften 16.04.

---

ASM-GUENTHER/README.md

Kann gerne noch ergänzt werden, falls PIA ein paar andere Inhalte hatte

ASM Mitschriften 23.04.21

---

ASM-GUENTHER/README.md

Das sollte eigentlich in @Steve2955's PR rein, aber da ist was schiefgelaufen. Daher lieber als separate PR

ASM: Binärschnittstelle

---

EMB-GUENTHER/README.md

Embedded Systems: Mitschriften 27.04.2019

---

DBS-DORENDORF/README.md

sind nicht ganz vollständig, können gerne noch ergänzt werden

DBS: Mitschriften 30.04.2021

---

ABWL-LEDER/README.md
EMB-GUENTHER/appendix/PRUEFUNGSAUFGABEN.md

Die Aufgaben aus den alternativen Prüfungsleistung für alle Gruppen.

EMB: Prüfungsaufgaben 2021

---

PRO-KASCHE/README.md

add changes as proposed by @photovoltex

Fix #34 pt2

---

PRO-KASCHE/README.md

Ich weiß nicht ganz, wie ihr das seht, aber ich wäre soweit das Ganze aufzugeben und die Tabelle durch einfache Stichpunkte zu ersetzen. Ohne Tabelle funktioniert die Umwandlung ohne Probleme 😅

Fix #34 part 3: surrender

---

ASM-GUENTHER/appendix/praktikum.md

Leider kam ich diesmal nicht ganz so flüssig durch - Ergänzungen sind sehr willkommen :-)

ASM vom 28.05.21

---

ASM-GUENTHER/README.md
DBS-DORENDORF/README.md
EMB-GUENTHER/README.md
OOP-CASSELT/README.md
SWE-KASCHE/appendix/LKF.md
SWS-KUSCHE/README.md

Änderungen aus der Besprechung und die Fragen der letzten Beiden Lernzielkontrollen

Neue Fragen und Teamsmeeting

---

SWE-KASCHE/README.md
SWE-KASCHE/appendix/LKF.md

+ Lint Check
Diesmal mit Entfernung von zuvor von @Steve2955 geschriebener Dinge, deswegen gleich eine PR.
Damit sind die Architektur-Muster der Sichten gemeint.

LKF-SysEntw. 1-4

---

ASM-GUENTHER/appendix/praktikum.md

Hier nochmal das Grimm-Praktikum, aber nur ergänzend. PIA ist wohl weiter gekommen

ASM (PIB) vom 03.06.21

---

SWE-KASCHE/README.md
SWE-KASCHE/appendix/LKF.md

LKF Teamsmeeting

---

ASM-GUENTHER/appendix/praktikum-cheatsheet.md

Falls wir sowas hier überhaupt nochmal brauchen 😅

Basic AVR Cheatsheet

---

MPP-PI/README.md

Ich habe mal die Themen, die wir von PI17 und PI15 bekommen haben, zusammengesammelt. Die Mitschriften von PI18 basieren wahrscheinlich auf den zuvor genannten. Da gab es sehr große Überschneidungen. PI15 hatte einen großen Fokus auf Betriebssystemen, der bei PI17 kaum vorhanden war. PI17 hatte eigentlich nur Rechnernetze und die typischen Kasche-Themen. Beim Lernen werde ich mich wahrscheinlich auch danach richten, gerade auch weil bei uns (zum Glück) kein Rauschenbach mit drin sitzt. 
Ziel wird es wahrscheinlich wieder sein, zu allen Themen kurz ein paar Stichpunkte zu schreiben (wie bei SWE).

MPP-Themen-Sammlung von PI18/17/15

---

MPP-PI/README.md

Die letzte PR ist etwas schiefgelaufen 😅

MPP Themen bearbeiten

---

.github/workflows/toc.yml

Implement proposed changes to fix #59

---

README.md

Hallo, ich hab für uns eine Orga erstellt, und bin jetzt dabei, ein paar Mitkommilitonen darin einzuladen. Könntet ihr bitte, wie hier im PR vorgeschlagen, den entsprechenden Link mit hinzufügen? Vlt. erreicht man so noch ein paar Leute.
Wenn ihr das so in Ordnung findet, würde ich für Semester 2 und 3 ebenfalls einen PR raussenden.
Danke!

Update README.md: Hinzufügen der PI20-Organisation

---

ABWL-LEDER/README.md

Rechtschreibung und Formulierung, QoL, BSC
inhaltliche Vervollständigung folgt

ABWL Readme changes
